---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ env "APP_NAME" }}
  namespace: {{ env "NAMESPACE" }}
  annotations:
    {{- if ne (env "NAMESPACE") "staging" }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    external-dns.alpha.kubernetes.io/hostname: {{ env "DOMAIN" }}
    kubernetes.io/ingress.class: {{ env "INGRESS_CLASS" }}
spec:
{{- if eq (env "NAMESPACE") "staging" }}
  tls:
  - hosts:
    - {{ env "DOMAIN" }}
    secretName: 
  - hosts:
    - {{ env "MAIN_DOMAIN" }}
    secretName: 
{{- else }}
  tls:
  - hosts:
    - {{ env "DOMAIN" }}
    secretName: {{ env "DOMAIN" }}-tls
  - hosts:
    - {{ env "MAIN_DOMAIN" }}
    secretName: {{ env "MAIN_DOMAIN" }}-tls
  {{- if eq (env "NAMESPACE") "production" }}
  # Support www. prefix on production
  - hosts:
    - www.{{ env "MAIN_DOMAIN" }}
    secretName: www.{{ env "MAIN_DOMAIN" }}-tls
  {{- end }}
{{- end }}
  rules:
  - host: {{ env "DOMAIN" }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ env "APP_NAME" }}
          servicePort: 80
  # Allow it to be requested by CNAME
  - host: {{ env "MAIN_DOMAIN" }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ env "APP_NAME" }}
          servicePort: 80
  {{- if eq (env "NAMESPACE") "production" }}
  # Support www. prefix on production
  - host: www.{{ env "MAIN_DOMAIN" }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ env "APP_NAME" }}
          servicePort: 80
  {{- end }}
