---
  kind: Service
  apiVersion: v1
  metadata:
    name: {{ env "APP_NAME" }}
    namespace: {{ env "NAMESPACE" }}
    labels:
      app: {{ env "APP_NAME" }}
  spec:
    type: NodePort
    sessionAffinity: ClientIP
    selector:
      app: {{ env "APP_NAME" }}
    ports:
      - name: web
        port: 80
        targetPort: 3000
      - name: metrics
        port: 10254
        targetPort: 10254
